databases:
  - name: postgres
    ipAllowList: []
    databaseName: foodie_render
    user: foodie_render

services:
  - type: web
    name: foodie
    env: ruby
    buildCommand: './render-build.sh'
    startCommand: 'bundle exec rails s'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
